export const FONTS = [
  { label: 'Anton', value: 'Anton' },
  { label: 'Cormorant', value: 'Cormorant' },
  { label: 'DM Sans', value: 'DM Sans' },
  { label: 'Hedvig', value: 'Hedvig' },
  { label: 'IBM Plex Sans', value: 'IBM Plex Sans' },
  { label: 'Instrument Sans', value: 'Instrument Sans' },
  { label: 'Inter', value: 'Inter' },
  { label: 'Lato', value: 'Lato' },
  { label: 'Libre Franklin', value: 'Libre Franklin' },
  { label: 'Manrope', value: 'Manrope' },
  { label: 'Open Sans', value: 'Open Sans' },
  { label: 'Pacifico', value: 'Pacifico' },
  { label: 'Playfair', value: 'Playfair' },
  { label: 'Poppins', value: 'Poppins' },
  { label: 'PT Sans', value: 'PT Sans' },
  { label: 'PT Serif', value: 'PT Serif' },
  { label: 'Raleway', value: 'Raleway' },
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Roboto Slab', value: 'Roboto Slab' },
  { label: 'Rubik', value: 'Rubik' },
  { label: 'Space Grotesk', value: 'Space Grotesk' },
  { label: 'Space Mono', value: 'Space Mono' },
  { label: 'Syne', value: 'Syne' },
  { label: 'Work Sans', value: 'Work Sans' }
];
